### ISSUE TITLE
README.md example may be incorrect

### ISSUE THREAD

**Issue by ghost** [scottrobertson/starling-export#1]
I believe the README.md launch examples may need updating.

I installed the dependencies:
gem install gemspec
gem install commander
gem install rest-client
gem install qif

I used:
ruby starling-export.rb qif --access_token _pasted-access-token_ --directory ~

**Comment by scottrobertson** [comment]
What error did you get?

**Comment by scottrobertson** [comment]
You can also just run `bundle` and it will install all the dependancies etc :)

**Comment by ghost** [comment]
Thanks!

If I use the example within README.md, I get "invalid option: --personal_token". To me, the source code looks like it requires two options, --access_token and --directory

**Comment by scottrobertson** [comment]
Yeah, it's access_token, will get that fixed :)
