### ISSUE TITLE
Ruby on Windows requires the csv file to already exist

### ISSUE THREAD

**Issue by dylmye** [scottrobertson/starling-export#2]
Hi. I'm new to Ruby so please excuse me if I'm wrong.
I got the following error after installing using bundle:

```
Q:\Downloads\Programs\starling-export-master>ruby starling-export.rb csv --access_token=[...]
error: No such file or directory @ rb_sysopen - ./tmp/starling.csv. Use --trace to view backtrace
```

I had to create the folder and file manually. Is this expected behaviour?

Thanks :)

**Comment by scottrobertson** [comment]
Very late reply.

If you create the `tmp` folder, it should work.
