### ISSUE TITLE
v1 API now EOL - update to v2?

### ISSUE THREAD

**Issue by shymega** [scottrobertson/starling-export#4]
The v1 API now EOL.

Could this project be updated to use v2?

**Comment by scottrobertson** [comment]
Happy to swap out the library we use to connect to their API if you can find a V2 one.

**Comment by shymega** [comment]
Looking at the code, there doesn't appear to be any library actually used for Starling's API...

Its done manually with the `RestClient` library.

**Comment by scottrobertson** [comment]
Ah yeah, forgot I built this one directly. I was thinking of another project. 

I don't have time at the moment, but I'll try and get to it sometime. 

Feel free to send a PR. Shouldn't be too much work.

**Comment by shymega** [comment]
Found [this](https://github.com/lildude/starling-export) last night. Perhaps a merge from that to this project might work?

**Comment by scottrobertson** [comment]
Can't really merge their one, as they have very custom/personal category mapping, but yeah it should not be too hard. Just don't have time right now sadly.

**Comment by scottrobertson** [comment]
Going to have a quick look now.

**Comment by scottrobertson** [comment]
Ah i see, you can only access transactions based on their category. What a terrible API design.

Feel free to PR something in, but this isn't something I am going to be able to spend much more time on today sadly.

**Comment by scottrobertson** [comment]
Or if @lildude wants to submit a PR to merge that version back in, that is fine too.

**Comment by lildude** [comment]
I've been meaning to submit a PR but got distract... ooooh, look a kite. 🤣 

I'm a little busy with work stuff at the mo, but I'm happy to whip things into shape and finish off all the other endpoints and submit a PR (without my custom stuff) in the next few weeks. I think I've got a few more local changes I've not pushed yet too.

**Comment by scottrobertson** [comment]
@shymega give that a go :)

**Comment by scottrobertson** [comment]
Note: transaction ids have changed, so you will see duplicates.

**Comment by shymega** [comment]
I get this error, weirdly:

```
error: undefined method `to_f' for {"currency"=>"GBP", "minorUnits"=>3000}:Hash
Did you mean?  to_s
               to_a
               to_h. Use --trace to view backtrace
```

Also, is there a way to remove those duplicates - or is that only for existing files?

**Comment by scottrobertson** [comment]
Sorry, by duplicates i mean if you are uploading this somewhere that uses the ids as the identifier. The id's have changed.

**Comment by scottrobertson** [comment]
Fixing that issue now.

**Comment by scottrobertson** [comment]
@shymega try now

**Comment by shymega** [comment]
@scottrobertson Works fine now. I'd like to suggest getting Bundler to install into a local `./vendor` directory (git-ignore'd of course), and making the script use the gems from that directory. 

What do you think? Happy to make a PR :ok_hand:

**Comment by scottrobertson** [comment]
It doesn't feel like that is something the app should enforce. You can change the folder gems install into by passing a flag go bundle.

**Comment by shymega** [comment]
Sure, that's fine. Thats what I do at the moment. 

Thanks for your response, though!
