### ISSUE TITLE
Script to read the token from an environmental variable?

### ISSUE THREAD

**Issue by shymega** [scottrobertson/starling-export#6]
I've been using the script, and passing the token via an environmental variable in the command line.

Currently, the script only accepts API tokens via a command line parameter, which if you then check the process list _whilst the script is running_, the token is then visible.

Perhaps the script could read the token from an environment variable, such as `STARLING_API_TOKEN`?

**Comment by scottrobertson** [comment]
Could you not just `--token $STARLING_API_TOKEN`

**Comment by shymega** [comment]
No. The shell will expand that variable when it runs the script, which will then appear in output from `ps aux`, for example.

**Comment by scottrobertson** [comment]
Makes sense. Feel free to PR :)

**Comment by shymega** [comment]
Does this extract from my branch look alright?

```ruby
    options.default \
      directory: "#{File.dirname(__FILE__)}/tmp",
      access_token: ENV["STARLING_ACCESS_TOKEN"]
```

**Comment by scottrobertson** [comment]
Yeah something like that should be fine :)
